# Identify this application
spring:
  application:
     name: accounts-service

# Eureka Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# Tomcat port
server:
  port: 2222