# Spring properties
spring:
  application:
    name: web-service  # Identify this application
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime

# Eureka Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# Tomcat port
server:
  port: 3333

# Set the error path
error:
  path=/error
