# Spring properties
spring:
  application:
    name: web-service  # Identify this application
  thymeleaf:
    cache=false # Allow Thymeleaf templates to be reloaded at dev time

# Eureka Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# Tomcat port
server:
  port: 3333

# Logging - NOTE these _cannot_ be loaded via @PropertySource
logging:
  level:
    org:
      springframework: WARN

# Set the error path
error:
  path=/error
